select II.ITEM_NO, AT.ATTRIBUTE_TYPE as TYPE, IA.VALUE 
from CB02KALS.ITEM_INFO ii, CB02KALS.item_attributes ia, CB02KALS.attribute_types at
where II.ITEM_INFO_ID = IA.ITEM_INFO_ID
and IA.ATTRIBUTE_TYPE_ID = AT.ATTRIBUTE_TYPE_ID
and II.ITEM_TYPE = 'G'
