select I.ITEM as ITEM_NO, IAT.ITEM_ATTRIBUTE_TYPE as TYPE, IAV.ITEM_ATTRIBUTE as VALUE
from CB02{{business}}.ITEMS i, CB02{{business}}.ITEM_ATTRIBUTE_TYPES iat, CB02{{business}}.ITEM_ATTRIBUTES ia, CB02{{business}}.ITEM_ATTRIBUTE_VALUES iav
where IA.ITEM_ATTRIBUTE_TYPE_ID = IAT.ITEM_ATTRIBUTE_TYPE_ID
and IA.ITEM_ID = I.ITEM_ID
and IAV.ITEM_ATTRIBUTE_ID = IA.ITEM_ATTRIBUTE_ID
and I.ITEM_KIND = 'G'
order by I.ITEM
