select I.ITEM as ITEM_NO, KT.KEYWORD_TYPE as TYPE, KP.KEYWORD_PHRASE as VALUE
from CB02{{business}}.ITEMS i, CB02{{business}}.KEYWORD_PHRASES kp, CB02{{business}}.KEYWORD_TYPES kt
where I.ITEM_ID = KP.ITEM_ID
and KP.KEYWORD_TYPE_ID = KT.KEYWORD_TYPE_ID
