select II.ITEM_NO, ACT.AD_COPY_TYPE as TYPE, ACC.AD_COPY as VALUE
from CB02KPNA.ITEM_INFO ii, CB02KPNA.AD_COPY ac, CB02KPNA.AD_COPY_TYPES act, CB02KPNA.AD_COPY_CHUNKS acc
where II.ITEM_INFO_ID = AC.ITEM_INFO_ID
and AC.AD_COPY_TYPE_ID = ACT.AD_COPY_TYPE_ID
and ACC.AD_COPY_ID = AC.AD_COPY_ID
and II.ITEM_NO in
    (select II2.ITEM_NO
    from CB02KPNA.ITEM_INFO ii1, CB02KPNA.ITEM_INFO ii2, CB02KPNA.ITEM_GROUPS ig
    where IG.ITEM_INFO_ID = II1.ITEM_INFO_ID
    and IG.ITEM_GROUP_ID = II2.ITEM_INFO_ID
    and II1.ITEM_NO in (select * from CB02KPNA.KPNA_WEB_VALID_SKUS))
order by II.ITEM_NO, ACT.AD_COPY_TYPE
