select distinct AT.ATTRIBUTE_TYPE as TYPE
from CB02KPNA.ITEM_INFO ii, CB02KPNA.item_attributes ia, CB02KPNA.attribute_types at
where II.ITEM_INFO_ID = IA.ITEM_INFO_ID
and IA.ATTRIBUTE_TYPE_ID = AT.ATTRIBUTE_TYPE_ID
and II.ITEM_TYPE = 'G'
