select distinct KT.KEYWORD_TYPE_UC as TYPE
from CB02KPNA.KEYWORDS k, CB02KPNA.KEYWORD_TYPES kt, CB02KPNA.KEYWORD_PHRASES kp, CB02KPNA.ITEM_INFO ii
where II.ITEM_INFO_ID = K.ITEM_INFO_ID
and K.KEYWORD_TYPE_ID = KT.KEYWORD_TYPE_ID
and K.PHRASE_ID = KP.PHRASE_ID