select distinct IAT.ITEM_ATTRIBUTE_TYPE as TYPE
from CB02NBKR.ITEMS i, CB02NBKR.ITEM_ATTRIBUTE_TYPES iat, CB02NBKR.ITEM_ATTRIBUTES ia, CB02NBKR.ITEM_ATTRIBUTE_VALUES iav
where IA.ITEM_ATTRIBUTE_TYPE_ID = IAT.ITEM_ATTRIBUTE_TYPE_ID
and IA.ITEM_ID = I.ITEM_ID
and IAV.ITEM_ATTRIBUTE_ID = IA.ITEM_ATTRIBUTE_ID
and I.ITEM_KIND = 'G'
