select II1.ITEM_NO, II2.ITEM_NO as VALUE, CST.CROSS_SELL_TYPE_UC as TYPE
from CB02KPNA.ITEM_INFO ii1, CB02KPNA.ITEM_INFO ii2, CB02KPNA.CROSS_SELLING cs, CB02KPNA.CROSS_SELLING_TYPES cst
where II1.ITEM_INFO_ID = CS.ITEM_INFO_ID
and CS.CROSS_SELL_TYPE_ID = CST.CROSS_SELL_TYPE_ID
and CS.CS_ITEM_INFO_ID = II2.ITEM_INFO_ID
and II1.ITEM_NO in (select * from CB02KPNA.KPNA_WEB_VALID_SKUS)
