select II.ITEM_NO, AT.ATTRIBUTE_TYPE as TYPE, IA.VALUE 
from CB02RBRN.ITEM_INFO ii, CB02RBRN.item_attributes ia, CB02RBRN.attribute_types at
where II.ITEM_INFO_ID = IA.ITEM_INFO_ID
and IA.ATTRIBUTE_TYPE_ID = AT.ATTRIBUTE_TYPE_ID
