select II.ITEM_NO, KT.KEYWORD_TYPE as TYPE, KP.PHRASE as VALUE
from CB02STRL.ITEM_INFO ii, CB02STRL.KEYWORDS k, CB02STRL.KEYWORD_PHRASES kp, CB02STRL.KEYWORD_TYPES kt
where II.ITEM_INFO_ID = K.ITEM_INFO_ID
and K.PHRASE_ID = KP.PHRASE_ID
and K.KEYWORD_TYPE_ID = KT.KEYWORD_TYPE_ID
and KT.KEYWORD_TYPE_ID = 1781 --gets us brand name
