select distinct CST.CROSS_SELL_TYPE_UC as TYPE
from CB02BAKR.ITEM_INFO ii, CB02BAKR.CROSS_SELLING cs, CB02BAKR.CROSS_SELLING_TYPES cst
where II.ITEM_INFO_ID = CS.ITEM_INFO_ID
and CS.CROSS_SELL_TYPE_ID = CST.CROSS_SELL_TYPE_ID
