select II1.ITEM_NO, II2.ITEM_NO as VALUE, CST.CROSS_SELL_TYPE_UC as TYPE
from CB02BAKR.ITEM_INFO ii1, CB02BAKR.ITEM_INFO ii2, CB02BAKR.CROSS_SELLING cs, CB02BAKR.CROSS_SELLING_TYPES cst
where II1.ITEM_INFO_ID = CS.ITEM_INFO_ID
and CS.CROSS_SELL_TYPE_ID = CST.CROSS_SELL_TYPE_ID
and CS.CS_ITEM_INFO_ID = II2.ITEM_INFO_ID
