select II.ITEM_NO, KT.KEYWORD_TYPE as TYPE, KP.PHRASE as VALUE
from CB02BAKR.KEYWORDS k, CB02BAKR.KEYWORD_TYPES kt, CB02BAKR.KEYWORD_PHRASES kp, CB02BAKR.ITEM_INFO ii
where II.ITEM_INFO_ID = K.ITEM_INFO_ID
and K.KEYWORD_TYPE_ID = KT.KEYWORD_TYPE_ID
and K.PHRASE_ID = KP.PHRASE_ID
